spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver
    #    url: jdbc:mysql://
    #    username: userId
    #    password: password
    #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
  hibernate:
    format_sql: true
    default_batch_fetch_size: 100
  h2:
    console:
    enabled: false
    #  sendgrid:
    #    api-key:
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  #  spring.jackson.serialization.fail-on-empty-beans: false
#server:
#  port: 80
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/itaxi?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false
#    username: root
#    password: itaxi2022!!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 100
#  h2:
#    console:
#      enabled: false
#    jackson:
#      serialization:
#      fail-on-empty-beans: false
#  logging:
#    level:
#      org.hibernate.SQL: debug
#      org.hibernate.type: trace